//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Members</summary>
	[PublishedContentModel("members")]
	public partial class Members : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "members";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Members(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Members, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address1
		///</summary>
		[ImplementPropertyType("address1")]
		public string Address1
		{
			get { return this.GetPropertyValue<string>("address1"); }
		}

		///<summary>
		/// Address2
		///</summary>
		[ImplementPropertyType("address2")]
		public string Address2
		{
			get { return this.GetPropertyValue<string>("address2"); }
		}

		///<summary>
		/// Email1
		///</summary>
		[ImplementPropertyType("email1")]
		public string Email1
		{
			get { return this.GetPropertyValue<string>("email1"); }
		}

		///<summary>
		/// Email2
		///</summary>
		[ImplementPropertyType("email2")]
		public string Email2
		{
			get { return this.GetPropertyValue<string>("email2"); }
		}

		///<summary>
		/// Name1
		///</summary>
		[ImplementPropertyType("name1")]
		public string Name1
		{
			get { return this.GetPropertyValue<string>("name1"); }
		}

		///<summary>
		/// Name2
		///</summary>
		[ImplementPropertyType("name2")]
		public string Name2
		{
			get { return this.GetPropertyValue<string>("name2"); }
		}

		///<summary>
		/// Skills1
		///</summary>
		[ImplementPropertyType("skills1")]
		public string Skills1
		{
			get { return this.GetPropertyValue<string>("skills1"); }
		}

		///<summary>
		/// Skills2
		///</summary>
		[ImplementPropertyType("skills2")]
		public string Skills2
		{
			get { return this.GetPropertyValue<string>("skills2"); }
		}
	}
}
